spring:
  datasource:
    dynamic:
      primary: mysql-test1
      datasource:
        mysql-test1:
          username: root
          password: 123456
          driver-class-name: com.mysql.cj.jdbc.Driver
          url: jdbc:mysql://192.168.48.128:3306/test
#        mysql-test2:
#          username: root
#          password: root
#          driver-class-name: com.mysql.cj.jdbc.Driver
#          url: jdbc:mysql://192.168.0.106:3306/test2
#        oracle-test:
#          username: TEST
#          password: 123123
#          driver-class-name: oracle.jdbc.driver.OracleDriver
#          url: jdbc:oracle:thin:@192.168.0.106:49161:XE
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
